### ISSUE TITLE
__init__.py has wrong version data

### ISSUE THREAD

**Issue by aknijn** [cov-lineages/pangoLEARN#72]
The __init__.py file of the pre-release 2022-02-28 still has the parameters of the previous version 2022-02-02 for __version__ and PANGO_VERSION

**Comment by aineniamh** [comment]
Thank you, I think it's been resolved now!

**Comment by corneliusroemer** [comment]
I think there's also a release still missing, at least according to the badge :) 
<img width="628" alt="image" src="https://user-images.githubusercontent.com/25161793/156804422-f0ae1237-cc5d-4230-b82c-6988a141e736.png">

**Comment by corneliusroemer** [comment]
Oh I see, the new one is a pre-release
